# Generated by Django 6.1.1 on 2026-09-13 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrotrace', '0004_auto_20260912_0942'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificacionLote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_auditoria', models.DateField()),
                ('codigo_inspeccion', models.CharField(max_length=50)),
                ('certificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agrotrace.certificacionagricola')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agrotrace.loterecepcionado')),
            ],
            options={
                'unique_together': {('lote', 'certificacion')},
            },
        ),
        migrations.AddField(
            model_name='loterecepcionado',
            name='certificaciones',
            field=models.ManyToManyField(related_name='lotes', through='agrotrace.CertificacionLote', to='agrotrace.certificacionagricola'),
        ),
        migrations.CreateModel(
            name='EvaluacionCalidadLote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_brix', models.DecimalField(decimal_places=2, max_digits=4)),
                ('firmeza_fruto', models.DecimalField(decimal_places=2, max_digits=4)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_evaluacion', models.DateField(auto_now_add=True)),
                ('lote', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluacion_calidad', to='agrotrace.loterecepcionado')),
            ],
        ),
    ]
